### ISSUE TITLE
Kanboard invalid volume specifications

### ISSUE THREAD

**Issue by Teenspirit** [chaosbunker/dockerbunker#11]
Hi,

I've gotten nextcloud and wekan to work, but for some reason when I try to install kanboard, I get this error : 

`docker: Error response from daemon: invalid volume specification: 'kanboard-db-vol-1:'.`

Which also results in the following when the nginx container is being restarted:

```
Restarting nginx container [failed]

2019/08/14 05:10:53 [emerg] 37#37: host not found in upstream "kanboard-service-dockerbunker:80" in /etc/nginx/conf.d/kan.yhelllothere.com.conf:26
nginx: [emerg] host not found in upstream "kanboard-service-dockerbunker:80" in /etc/nginx/conf.d/kan.yhellothere.com.conf:26
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Appreciate any help.

**Comment by chaosbunker** [comment]
Just fixed this, thanks for pointing it out.

dockerbunker will only restart nginx if `nginx -t` is successful. If it was blindly restarted it would break and not serve any other service that's set up until it's fixed.

In this case nginx couldn't find the host `kanboard-service-dockerbunker:80`, since the container `kanboard-service-dockerbunker` couldn't be created, because a non-existent volume (`kanboard-db-vol-1`) was specified in the `docker run` command (see [commit](https://github.com/chaosbunker/dockerbunker/commit/e4598a8ff894b82c554c7f74af37d853d7aec178)). The correct volume name that should have been (and now is) specified is `kanboard-data-vol-2`.

**Comment by Teenspirit** [comment]
Noob to github, hope this doesn't reopen it, but would like to thank you for this awesome script. And also to say that I'm disappointed that I didn't figure that out myself.

**Comment by chaosbunker** [comment]
Haha, no worries. I'm sure it would be easier to figure things out had I done a better job at documenting how everything is put together:)

It's nice to hear that dockerbunker is useful to others!
