### ISSUE TITLE
destroy everything wont destroy everything

### ISSUE THREAD

**Issue by stephanfriedrich** [chaosbunker/dockerbunker#13]
hi thx again for your awesome work.

i installed one service eg. Kanboard with your tool.
then i tried to destroyed this service with **"36) Destroy everything"**, but it seams this task wont destroy the container oder image. if i run dockerbunker to reinstall Kanboard egain, i got these issue :

```Starting up nginx containerdocker: Error response from daemon: Conflict. The container name "/nginx-dockerbunker" is already in use by container "90a2ae2d06f1a90c98a35927bb762f397de00549711d95cd26168b0949a60b9e". You have to remove (or rename) that container to be able to reuse that name.```

**GNU bash, Version 4.4.20(1)**
**mint 5.2.15-050215-generic**

**Comment by stephanfriedrich** [comment]
with ```docker container ls```
the previously created container is still alive 
```cf2d89f3562e        kanboard/kanboard:v1.2.1   "/usr/local/bin/entr…"   4 hours ago         Up 4 hours          80/tcp              kanboard-service-dockerbunker```

**Comment by chaosbunker** [comment]
I figured out why the nginx container wasn't destroyed and will fix that (e.g. if the container is restarting it would not be destroyed). Not clear why kanboard would still be there and couldn't reproduce that part. If you did `docker container ls` after reinstalling kanboard that would explain why. Because even though the setup  of nginx fails due to the naming conflict you reported, the kanboard container is successfully created.

You can now manually remove nginx-dockerbunker with `docker rm -f nginx-dockerbunker` and then reinstalling after "destroy all" should work as expected.

If you just want to reinstall kanboard or reconfigure it, you could do that in the menu for kanboard (or any other service). No need to destroy everything:)

**Comment by chaosbunker** [comment]
Fixed via [8fae20d ](https://github.com/chaosbunker/dockerbunker/commit/8b626750742f8801775766f8e3391a47a65cab40)
